### ISSUE TITLE
[Feature Request] Maybe add "Data" toggle?

### ISSUE THREAD

**Issue by volnes** [vackosar/search-based-launcher#16]
WiFi toggle here. 
Bluetooth toggle here.
Camera here too!
Maybe add Data toggle?) above wifi toggle?
How do u think @vackosar ? its good idea?

**Comment by Ferk** [comment]
IMHO, it would be cool if the stuff set in the right area as "stickies" was more customizable.

Not everyone is gonna need bluetooth or data or camera buttons in there.
Also, changing the name of those stiky icons would be nice. Possibly being able to use some [unicode emoji](https://en.wikipedia.org/wiki/Emoji) to make them more visually recognizable.

They should also have some background or something, sometimes it's possible to click through them, causing an activity item to launch instead of the toggle, which is kind of annoying.

**Comment by vackosar** [comment]
@Ferk, you can submit your request as a separate ticket/issue:
- I think you have a point regarding collapsing space if feature is not present.
- I like the idea of reducing posibility of click throughts.
- I don't like playing with the icons however. Maybe later.

**Comment by vackosar** [comment]
@volnes, I attempted to implement this feature already twice and failed. It is too challenging with API 7. What you can do however is to "Add" a activity for controlling the data to speed up your way to the settings.

**Comment by volnes** [comment]
@vackosar oh, thanks! i try!
